---
title: "Academic & Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: journal
---

### Education
Columbia University Mailman School of Public Health, New York, NY     
Master of Public Health in Epidemiology, Applied Biostatistics Certificate (Expected May 2020)


McGill University, Montreal, QC, Canada 	
Bachelor of Science in Physical (Health) Geography, Economics (May 2018)          



### Non-Profit & Government Public Health Research Experience
**Columbia University, New York, NY**      
Department of Epidemiology
Graduate Research Assistant     
*September 2019 – Present*

* Working on a new research study of nutrition, early detection, and cancer risk and survival (primarily focused on ovarian and pancreatic cancers)
* Conducting pooled analyses, systematic reviews, data entry, cleaning, data analysis and literature searches, updating research databases, creating tables, graphs, and spreadsheets, preparing PowerPoint presentations, and performing word processing for scientific manuscripts

**EcoHealth Alliance, New York, NY**     
EcoHealthNet Research Exchange Intern     
*May – August 2019*

* Worked specifically on the Western Asia Bat Research Network Project (WAB-Net) which is fully funded by the Cooperative Biological Engagement Program of the United States Department of Defense – Defense Threat Reduction Agency
* Completed a broad zoonotic disease research review and research pre-existing, publicly-available datasets to potentially use
* Conducted a network analysis on livestock trade and disease prevalence of Western Asia countries with R
* Collected diagnostic samples from wild-caught bats for coronavirus surveillance in Turkey and Jordan in August 2019


**National Center for Disaster Preparedness, New York, NY**     
Graduate Research Assistant     
*January – May 2019*

*	Built an open-access topical application using ArcGIS which will serve as supplemental material to FEMA Community Housing Recovery trainings throughout the United States
*	Curated housing, community, and natural hazards Geographic Information Systems (GIS) assets based on existing literature regarding community housing recovery after disasters
*	Cleaned and manipulated curated datasets in Stata
*	Spatially joined housing, community, and natural hazards GIS datasets to a Census Tract geodatabase


**US Department of the Interior, Washington, DC**     
National Park Service, Office of Public Health, Disease Prevention and Response Epidemiology Branch
Epidemiology Student Trainee     
*June – August 2018*

*	Developed content (e.g., infectious disease fact sheets) for the National Park Service internal and external websites
*	Evaluated Appalachian Trail’s current norovirus surveillance system to identify strengths and gaps
*	Used CDC software EpiInfo to develop and deploy disease detection survey for norovirus cases in Yellowstone National Park 
*	Performed fieldwork (tick dragging) for multi-year CDC Lyme disease surveillance project in Rock Creek Park, Maryland


**American Society for Microbiology, Washington, DC**     
International Affairs Team Program Coordinator     		  
*June – August 2018*

*	Provided administrative and logistical support for three major programs: PEPFAR (CDC), Global Health Security Agenda (CDC), and Biosafety & Biosecurity (BS&S) strengthening (Department of State)
*	Researched public and private funding opportunities for One Health and point-of-care HIV testing
*	Spearheaded effort to create partnerships between ASM and multiple Chinese organizations, including China CDC, and universities

**Land and Food Lab, McGill University, Montreal, QC, Canada**     
Research Assistant     
*January – May 2018*     

*	Developed a phosphorus footprint tool based on U.S. data which describes the phosphorus losses to the environment that are linked to individual or collective consumption patterns
*	Compiled and manipulated data in Microsoft Excel to a generate set of calculations called virtual phosphorus factors (VPFs) for animal-based products
*	Initially my independent research project for Fall 2017, continued on as Research Assistant in the lab for Winter 2018



### Awards, Presentations & Publications
*	**Best Poster of Infectious Disease Epidemiology Award**, Columbia University 9th Annual Epidemiology Master’s Student Day, October 2019
*	**Speaker Presentation**, “Building a Community Based Housing Disaster Recovery GIS Application,” Earth Science Information Partners Annual Meeting, July 2019
*	**Graduate Student Panelist**, Columbia University’s Biostatistics Epidemiology Summer Training (BEST) Diversity Program, June 2019
*	**Manuscript Publication**, “Blending Sequencing and Scientific Engagement: Achieving Biological Threat Reduction and Global Health Security,” Tropical Medicine and Infectious Disease Journal, Published May 2019
*	**Poster Presentation**, “Creating a Knowledge Sharing Hub for Biosecurity Using an Online Collaborative Tool,” American Public Health Laboratories Annual Meeting, June 2018
*	**Speaker Presentation**, “A Next-Generation Research and Knowledge Sharing Hub for Biosecurity,” Sequencing, Finishing, and Analysis in the Future (SFAF) Annual Meeting, May 2018
*	**Poster Presentation**, “Examining the Impact of the Schistosomiasis Control Initiative on Praziquantel Coverage in Sub-Saharan African Schoolchildren,” American Society of Tropical Medicine and Hygiene 66th Annual Meeting, November 2017
*	**First Place Prize**, “NTI-GHSN   Biosecurity   Competition   Proposal:   Addressing   Biosecurity   and   Associated Technological   Risks   by   Creating   a   Database   to   Knowledge-sharing   and   Utility,” 2017 Nuclear Threat Initiative-Next Generation Global Health Security Network Biosecurity in the Global Health Security Agenda (GHSA) Competition for the 4th Annual High Level GHSA Ministerial Meeting in Kampala, Uganda, October 2017



### Community Experience
*	**Volunteer**, New York Cares, New York, New York, April 2019 – Present
*	**Competition Proposal Judge**, Nuclear Threat Initiative-Next Generation Global Health Security Network’s Biosecurity in the Global Health Security Agenda (GHSA) Competition, Fall 2018 & 2019
*	**Volunteer**, Salvation Army FeedMore Program, Baltimore, Maryland, 2004 – Present
*	**Volunteer**, Evergreen Senior Care, Washington, DC, 2010 – Present
*	**Meeting with the United States National Security Council**, The White House, Washington, DC, December 2017


